version = 0.1

[default.deploy.parameters]
stack_name = "escape-cville-app"
resolve_s3 = true
s3_prefix = "escape-cville-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["IngestFunction=045511193184.dkr.ecr.us-east-1.amazonaws.com/escapecvilleappd987eede/ingestfunction3c3588cfrepo"]

[default.global.parameters]
region = "us-east-1"

