AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: escape-cville-table
        REGION: us-east-1
        S3_BUCKET: escape-cville-bucket

Resources:
  IngestFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: latest
      DockerContext: ./ingest
      Dockerfile: Dockerfile
    Properties:
      FunctionName: escape-cville-ingest
      PackageType: Image 
      ImageUri: ingest:latest 

      MemorySize: 300
      Environment:
        Variables:
          MPLCONFIGDIR: /tmp/matplotlib
      
      Events:
        IngestSchedule:
          Type: Schedule
          Properties:
            Name: ingest-every-20min
            Schedule: cron(0/20 * * * ? *) # every 20min
            Enabled: true
        # FrequentSchedule:
        #   Type: Schedule
        #   Properties:
        #     Name: ingest-every-15min-daytime
        #     Schedule: cron(0/15 10-23 * * ? *) # 6:00am-7:45pm EDT, every 15min
        #     Enabled: true
        # InfrequentSchedule:
        #   Type: Schedule
        #   Properties:
        #     Name: ingest-every-30min-overnight
        #     Schedule: cron(0/30 0-9 * * ? *) # 8:00pm-5:30am EDT, every 30min
        #     Enabled: true

      Policies:
        - DynamoDBWritePolicy:
            TableName: escape-cville-table
        - DynamoDBReadPolicy:
            TableName: escape-cville-table
        - Statement:
          # Allow access to SSM and KMS
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: arn:aws:ssm:us-east-1:045511193184:parameter/escape-cville/here-api-key
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource: "*"
          
          # Allow access to S3
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::escape-cville-bucket/*
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::escape-cville-bucket
              